### ISSUE TITLE
JP - Story Balance patch corrupts Spell Card names

### ISSUE THREAD

**Issue by alexstrout** [SuperChrim/SuperChrim#2]
Hello! When using the StoryBalance patch on its own without the EN patch applied, Spell Card names appear to get corrupted:

![20240510213929_1](https://github.com/SuperChrim/SuperChrim/assets/3589969/03906b43-f501-43d5-90b8-4378d7980e15)

However, the Balance patch on its own appears as expected:

![20240510220552_1](https://github.com/SuperChrim/SuperChrim/assets/3589969/ddc55011-099d-4e70-8ab2-09bf23be1562)

Using EN + StoryBalance patch also appears as expected:

![20240510214722_1](https://github.com/SuperChrim/SuperChrim/assets/3589969/bff349ff-9bfc-4cd1-a927-217a6c039d4d)

This behaviour was noted as of yesterday, commit dc3d91b, and was reproducible in both Story and VS modes (human or CPU). I haven't tested since then.

Contents of `Th19StoryBalance.js`, in case it's at all useful:
```js
{
  "dat_dump": false,
  "patched_files_dump": false,
  "patches": [
    {
      "archive": "repos/nmlgc/base_tsa/"
    },
    {
      "archive": "repos/zero318/ZeroEclExtensions/"
    },
    {
      "archive": "repos/Shoxlu/Th19FixOrinLV2/"
    },
    {
      "archive": "repos/Shoxlu/Th19ExAttackResAnimFix/"
    },
    {
      "archive": "repos/SuperChrim/Th19BugFixes/"
    },
    {
      "archive": "repos/SuperChrim/Th19Balance/"
    },
    {
      "archive": "repos/SuperChrim/Th19StoryBalance/"
    }
  ]
}
```

LMK if there's anything else I can provide that could help. Thank you!

**Comment by SuperChrim** [comment]
Thank you for the report. The issue has now been fixed.
